name: B&P Python package with PyInstaller

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-executables:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: python -m pip install --upgrade pip
    - run: pip install pyinstaller

    - run: pyinstaller --onefile main.py
      shell: bash

    - id: prepare_artifact
      run: |
        EXECUTABLE_NAME=$(basename "main")
        FOUND_EXECUTABLE=$(find dist -maxdepth 1 -name "${EXECUTABLE_NAME}*" -print -quit)

        if [ -z "$FOUND_EXECUTABLE" ]; then
          echo "Error: Executable not found in 'dist' folder. Check your PyInstaller command and 'main.py' path."
          exit 1
        fi

        ARTIFACT_NAME="${EXECUTABLE_NAME}-ubuntu"
        mv "${FOUND_EXECUTABLE}" "${ARTIFACT_NAME}"
        
        echo "artifact_path=${{ github.workspace }}/${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
        echo "asset_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.prepare_artifact.outputs.artifact_path }}
        asset_name: ${{ steps.prepare_artifact.outputs.asset_name }}
        asset_content_type: application/octet-stream
